#vaivora_modules.disclaimer
disclaimer = """
```diff
+ By allowing Wings of Vaivora access to your server, you agree to the terms outlined below.
- If you disagree, please revoke authorization for Wings of Vaivora.
--- Terms ---
--- 2017/08/22, v.1 ---
+ Data is not collected from users in an identifiable way. All data stored is in the form of IDs generated by discord.py.
- However, please be aware that features later may involve personally identifiable data collection.
-   Wings of Vaivora will have changes to the disclaimer for each of these updates. It is up to you to allow or deny.
```
"""