#!/usr/bin/env python
import sys
from inspect import cleandoc

import discord
import yaml
from discord.ext import commands

import cogs.boss
import vaivora.common
import vaivora.db


BOT = commands.Bot(command_prefix=['v!'])

INITIAL_EXTENSIONS = [
    'cogs.admin',
    'cogs.boss',
    'cogs.events',
    'cogs.gems',
    'cogs.meme',
    'cogs.offset',
    'cogs.settings',
    ]

# snippet from https://gist.github.com/EvieePy/d78c061a4798ae81be9825468fe146be
if __name__ == '__main__':
    with open('config.yaml', 'r') as f:
        CONF = yaml.safe_load(f)

    for extension in INITIAL_EXTENSIONS:
        try:
            BOT.load_extension(extension)
        except Exception as e:
            print(
                f'Failed to load extension {extension}: {e}',
                file=sys.stderr
                )

# One of these days
BOT.remove_command('help')

TERMS = """
By allowing Wings of Vaivora access to your server, you agree to the terms outlined below.

[1.1] - 2019-08-15
---
Data is not collected from users in a personally identifiable way. All data stored is in the form of IDs generated by `discord.py`.
If, and when, features change to request personally identifiable information, you will be asked to agree to the new terms.
**You may decline to accept the new terms; you will not be able to access the functionality that requests this information.**
For the foreseeable future, no such features are planned.
"""

WELCOME = """
Thank you for inviting me to your server!
I am a representative bot for the Wings of Vaivora, here to help you record your journey.
Please read the following before continuing.
""" + TERMS + """
Anyone may contribute to this bot's development: https://github.com/dark-nova/wings-of-vaivora
"""

HELP = """
Here are commands. Valid prefixes are `$` (dollar sign) and `Vaivora,<space>`,
e.g. `$boss` or `Vaivora, help`

`$boss` commands
More info: <https://github.com/dark-nova/wings-of-vaivora/blob/master/docs/BOSS.md>

`$settings` commands
More info: <https://github.com/dark-nova/wings-of-vaivora/blob/master/docs/SETTINGS.md>

`$gems` commands
More info: <https://github.com/dark-nova/wings-of-vaivora/blob/master/docs/GEMS.md>

`$offset` commands
More info: <https://github.com/dark-nova/wings-of-vaivora/blob/master/docs/OFFSET.md>

General
```
$help: prints this page in Direct Message
```
"""

@BOT.event
async def on_ready() -> None:
    """Handles whenever the bot is ready."""
    print("Logging in...")
    print(
        cleandoc(
            f"""Successsfully logged in as:
            - {BOT.user.name}#{BOT.user.discriminator}: ID {BOT.user.id}.
            Ready!"""
            )
        )


@BOT.event
async def on_guild_join(guild: discord.Guild) -> None:
    """Handles what to do when a guild adds Wings of Vaivora.

    Args:
        guild (discord.Guild): the guild which this client has joined

    """
    if guild.unavailable:
        return

    guild_db = vaivora.db.Database(guild.id)
    await guild_db.create_all(guild.owner.id)

    await guild.owner.send(WELCOME)


@BOT.command(aliases=['halp'])
async def help(ctx) -> None:
    """Retrieves the help pages for `$help`."""
    await ctx.author.send(HELP)


if __name__ == '__main__':
    BOT.loop.run_until_complete(BOT.start(CONF['discord_token']))
