#vaivora_constants.regex.settings.command
import re

prefix      = re.compile(r'(va?i(v|b)ora, |\$)settings?', re.IGNORECASE)
abrackets   = re.compile(r'[<>]')
cmd_all     = re.compile(r'(((un)?s|g)et|rm|(un)?verify|(in)?valid(ate)?|(pro|de)mote|help|reset|add)', re.IGNORECASE)
cmd_prdm    = re.compile(r'(pro|de)mote', re.IGNORECASE)
cmd_pr      = re.compile(r'promote', re.IGNORECASE)
cmd_dm      = re.compile(r'demote', re.IGNORECASE)
cmd_getset  = re.compile(r'(s|g)et', re.IGNORECASE)
cmd_set     = re.compile(r'set', re.IGNORECASE)
cmd_reset   = re.compile(r'reset', re.IGNORECASE)
cmd_get     = re.compile(r'get', re.IGNORECASE)
cmd_gs2     = re.compile(r'(talt|ch(an(nel)*)?|roles?|guild)', re.IGNORECASE)
cmd_gs23    = re.compile(r'ch(an(nel)*)?', re.IGNORECASE)
cmd_gs3     = re.compile(r'(ma?na?ge?(me*nt)?|boss)', re.IGNORECASE)
cmd_ch      = re.compile(r'^<#[0-9]+>$', re.IGNORECASE)
cmd_ch_mgmt = re.compile(r'ma?na?ge?(me*nt)?', re.IGNORECASE)
cmd_ch_boss = re.compile(r'boss', re.IGNORECASE)
cmd_rm      = re.compile(r'(rm|unset)', re.IGNORECASE)
cmd_add     = re.compile(r'add', re.IGNORECASE)
cmd_allv    = re.compile(r'((un)?verify|(in)?valid(ate)?)', re.IGNORECASE)
cmd_un      = re.compile(r'^[iu]n', re.IGNORECASE)
cmd_valid   = re.compile(r'(verify|valid(ate)?)', re.IGNORECASE)
cmd_talt    = re.compile(r'talt', re.IGNORECASE)
cmd_rebase  = re.compile(r'rebase', re.IGNORECASE)
cmd_role    = re.compile(r'roles?', re.IGNORECASE)
cmd_roles   = re.compile(r'(s(uper)*[ -])?(auth(orized?)*|member|boss)', re.IGNORECASE)
cmd_role_s  = re.compile(r'(s(uper)*[ -])auth(orized)', re.IGNORECASE)
cmd_role_a  = re.compile(r'auth(orized?)*', re.IGNORECASE)
cmd_role_m  = re.compile(r'member', re.IGNORECASE)
cmd_talts   = re.compile(r'^[0-9]+ ?t(alt)?s?$', re.IGNORECASE)
cmd_tpoint  = re.compile(r'^[0-9]+ ?p(oin)?ts?$', re.IGNORECASE)
cmd_tallt   = re.compile(r'all', re.IGNORECASE)
cmd_guild   = re.compile(r'guild', re.IGNORECASE)
cmd_numbers = re.compile(r'[0-9]+')
cmd_temp    = re.compile(r'temp(orary)?', re.IGNORECASE)